version: "3"
services:
  pgrouting:
    image: pgrouting/pgrouting:17-3.5-develop
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
volumes:
  db-data:
